[2024-12-23T13:17:19.180+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-23T13:17:19.341+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_spark_cluster.spark_action manual__2024-12-23T13:17:09.986397+00:00 [queued]>
[2024-12-23T13:17:19.368+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_spark_cluster.spark_action manual__2024-12-23T13:17:09.986397+00:00 [queued]>
[2024-12-23T13:17:19.369+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-23T13:17:19.401+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): spark_action> on 2024-12-23 13:17:09.986397+00:00
[2024-12-23T13:17:19.437+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2592) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-23T13:17:19.443+0000] {standard_task_runner.py:72} INFO - Started process 2595 to run task
[2024-12-23T13:17:19.442+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_spark_cluster', 'spark_action', 'manual__2024-12-23T13:17:09.986397+00:00', '--job-id', '241', '--raw', '--subdir', 'DAGS_FOLDER/dag_spark_cluster.py', '--cfg-path', '/tmp/tmpcu1vjh8z']
[2024-12-23T13:17:19.446+0000] {standard_task_runner.py:105} INFO - Job 241: Subtask spark_action
[2024-12-23T13:17:19.594+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_spark_cluster.spark_action manual__2024-12-23T13:17:09.986397+00:00 [running]> on host 85f5ad808200
[2024-12-23T13:17:19.885+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_spark_cluster' AIRFLOW_CTX_TASK_ID='spark_action' AIRFLOW_CTX_EXECUTION_DATE='2024-12-23T13:17:09.986397+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-23T13:17:09.986397+00:00'
[2024-12-23T13:17:19.889+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-23T13:17:20.665+0000] {logging_mixin.py:190} INFO - Error starting Spark Master: 409 Client Error for http+docker://localhost/v1.47/containers/create?name=spark-master: Conflict ("Conflict. The container name "/spark-master" is already in use by container "32c31757cd83af4f6497250c142d8f483904d5e3bbd020ca30babd31fc495280". You have to remove (or rename) that container to be able to reuse that name.")
[2024-12-23T13:17:21.183+0000] {logging_mixin.py:190} INFO - Error starting Spark Worker: 409 Client Error for http+docker://localhost/v1.47/containers/create?name=spark-worker: Conflict ("Conflict. The container name "/spark-worker" is already in use by container "a84ef08aaae7fde5350fb8004674282c9e4df3177cd4babf292d4f311fda93eb". You have to remove (or rename) that container to be able to reuse that name.")
[2024-12-23T13:17:21.188+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-23T13:17:21.299+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-23T13:17:21.302+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_spark_cluster, task_id=spark_action, run_id=manual__2024-12-23T13:17:09.986397+00:00, execution_date=20241223T131709, start_date=20241223T131719, end_date=20241223T131721
[2024-12-23T13:17:21.416+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-23T13:17:21.531+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-23T13:17:21.542+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
