[2024-12-24T03:24:39.895+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-24T03:24:39.907+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_spark_cluster.spark_action manual__2024-12-24T03:24:38.978830+00:00 [queued]>
[2024-12-24T03:24:39.913+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_spark_cluster.spark_action manual__2024-12-24T03:24:38.978830+00:00 [queued]>
[2024-12-24T03:24:39.915+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-24T03:24:39.923+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): spark_action> on 2024-12-24 03:24:38.978830+00:00
[2024-12-24T03:24:39.928+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=113) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-24T03:24:39.929+0000] {standard_task_runner.py:72} INFO - Started process 117 to run task
[2024-12-24T03:24:39.929+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_spark_cluster', 'spark_action', 'manual__2024-12-24T03:24:38.978830+00:00', '--job-id', '295', '--raw', '--subdir', 'DAGS_FOLDER/dag_spark_cluster.py', '--cfg-path', '/tmp/tmpdk9d3exk']
[2024-12-24T03:24:39.930+0000] {standard_task_runner.py:105} INFO - Job 295: Subtask spark_action
[2024-12-24T03:24:39.962+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_spark_cluster.spark_action manual__2024-12-24T03:24:38.978830+00:00 [running]> on host 6623c32d3eea
[2024-12-24T03:24:40.013+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_spark_cluster' AIRFLOW_CTX_TASK_ID='spark_action' AIRFLOW_CTX_EXECUTION_DATE='2024-12-24T03:24:38.978830+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-24T03:24:38.978830+00:00'
[2024-12-24T03:24:40.014+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-24T03:24:40.221+0000] {logging_mixin.py:190} INFO - Error starting Spark Master: 409 Client Error for http+docker://localhost/v1.47/containers/create?name=spark-master: Conflict ("Conflict. The container name "/spark-master" is already in use by container "233a4c7496de815f41df4d59ae4b1783bff7aa40f2f20886b686cadd7e945ad1". You have to remove (or rename) that container to be able to reuse that name.")
[2024-12-24T03:24:40.302+0000] {logging_mixin.py:190} INFO - Error starting Spark Worker: 409 Client Error for http+docker://localhost/v1.47/containers/create?name=spark-worker: Conflict ("Conflict. The container name "/spark-worker" is already in use by container "53b87f6574a89bb20f335f0ffa71fc35a247aae683e57859dfd9474cdb5cedb9". You have to remove (or rename) that container to be able to reuse that name.")
[2024-12-24T03:24:40.304+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-24T03:24:40.328+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-24T03:24:40.332+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_spark_cluster, task_id=spark_action, run_id=manual__2024-12-24T03:24:38.978830+00:00, execution_date=20241224T032438, start_date=20241224T032439, end_date=20241224T032440
[2024-12-24T03:24:40.357+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-24T03:24:40.424+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-24T03:24:40.426+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
